src/Entity/Produit.php
<?php

namespace App\Entity;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Genre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $marque;

    public function __construct()
    {

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(?string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }
    public function __toString()
    {
        return  $this->titre;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Entity\Commande;
use App\Entity\CommandeProduit;


use App\Form\CommandeProduitFormType;
use App\Repository\ProduitRepository;

use Doctrine\ORM\EntityManagerInterface;
use App\Repository\FournisseurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(ProduitRepository $produitRepository , FournisseurRepository $fournisseurRepository): Response
    {

        return $this->render('home/index.html.twig', [
            'produits' => $produitRepository->findAll()
        ]);
    }


    /**
     * @Route("/produit/{id}", name="produit")
     */
    public function show(Request $request, Produit $produit, EntityManagerInterface $em): Response
    {

        $commandeProduit = new CommandeProduit();

        $form = $this->createForm( CommandeProduitFormType::class, $commandeProduit);

        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){
            //dd($form->get('quantite')->getData());
            $manager = $this->getDoctrine()->getManager();
            $repo = $manager->getRepository(Commande::class);
            $repo2 = $manager->getRepository(CommandeProduit::class);

            $commande = $repo->findOneBy([
                'utilisateur' => $this->getUser(),
                "status" => 0
            ]);

    
            if(is_null($commande)){
                $commande = new Commande();
                $commande
                    ->setUtilisateur($this->getUser())
                    ->setDate(new \Datetime())
                    ->setStatus(0)
                    ;
            }
            $commandeProduitfind=$repo2->findOneBy([
                'produit' => $produit,
                "commande" => $commande
            ]);
            if(!is_null($commandeProduitfind)){
                $commandeProduit=$commandeProduitfind;
                $commandeProduit->setQuantite( $commandeProduit->getQuantite() + $form->get('quantite')->getData() );
            }
            

            if($commandeProduit->getquantite() == $form->get('quantite')->getData()){
                $commandeProduit->setProduit($produit);
                $commandeProduit->setCommande($commande);

                $commande->addCommandeProduit($commandeProduit);
            }
            

            $manager->persist($commande);
            $manager->persist($commandeProduit);

            $manager->flush();

            $this->addFlash('success', 'Le produit est ajouté à votre commande actuel');

        }


        return $this->render('home/produit.html.twig', [
            'produit' => $produit, 
            'commandeForm'=>$form->createView()
        ]);
    }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <!-- section title -->
    <div class="col-md-12">
        <div class="section-title">
            <h3 class="title">Les produits</h3>
            
        </div>
    </div>
    <!-- /section title -->

    <!-- Products tab & slick -->
    <div class="col-md-12">
        <div class="row">
            <div class="products-tabs">
                <!-- tab -->
                <div id="tab1" class="tab-pane active">
                    <div class="products-slick" data-nav="#slick-nav-1">
                            {% for produit in produits %}
                        <!-- product -->
                        <div class="product">
                            <div class="product-img">
                                <img src="./img/voiture{{ produit.id % 4 }}.jpg" alt="">
                            </div>
                            <div class="product-body">
                                <p class="product-category">{{ produit.marque.nom }}</p>
                                <h3 class="product-name"><a href="{{ path('produit', { id: produit.id }) }}">{{ produit.titre }}</a></h3>
                                <h4 class="product-price">€{{ produit.prix }} </h4>
                                
                            </div>
                            <div class="add-to-cart">
                                <form action='{{ path('produit', { id: produit.id }) }}'>    
                                <button  class="add-to-cart-btn"><i class="fa fa-eye"></i>Voir fiche</button>
                                </form>
                            </div>
                        </div>
                        <!-- /product -->
                            {% endfor %}

                    </div>
                    <div id="slick-nav-1" class="products-slick-nav"></div>
                </div>
                <!-- /tab -->
            </div>
        </div>
    </div>
    <!-- Products tab & slick -->
{% endblock %}

templates/home/produit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ produit.titre }}{% endblock %}

{% block body %}

<!-- Product main img -->
<div class="col-md-5 col-md-push-2">
    <div id="product-main-img">
        <div class="product-preview">
            <img src="{{ asset('/img/voiture0.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture1.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture2.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture3.jpg') }}" alt="">
        </div>
    </div>
</div>
<!-- /Product main img -->

<!-- Product thumb imgs -->
<div class="col-md-2  col-md-pull-5">
    <div id="product-imgs">
        <div class="product-preview">
            <img src="{{ asset('/img/voiture0.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture1.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture2.jpg') }}" alt="">
        </div>

        <div class="product-preview">
            <img src="{{ asset('/img/voiture3.jpg') }}" alt="">
        </div>
    </div>
</div>
<!-- /Product thumb imgs -->

<!-- Product details -->
<div class="col-md-5">
    <div class="product-details">
        <h2 class="product-name">{{ produit.titre }}</h2>
        <div>
            <div class="product-rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            
        </div>
        <div>
            <h3 class="product-price">€{{ produit.prix }}</h3>
            <span class="product-available">{{ produit.quantite ==0 ? 'RUPTURE DE STOCK':'DISPONIBLE' }} </span>
        </div>
        <p>{{ produit.description }}</p>

        <div class="add-to-cart">
            
            {% if app.user %}
            {{ form_start(commandeForm) }}
                <div class="form-group">
                    {{ form_row(commandeForm.quantite) }}
                </div>
                {{ form_row(commandeForm.valider) }}

            {{ form_end(commandeForm) }}
            {% else %}
                <form action='{{ path('app_register') }}'>
                    <button class="add-to-cart-btn"><i class="fa fa-link"></i> S'inscrire pour commander</button>
                </form>
            {% endif %}
            
        </div>

       
        <ul class="product-links">
            <li>Genre:</li>
            <li>{{ produit.genre }}</li>
        </ul>
        
        <ul class="product-links">
            <li>Type:</li>
            <li>{{ produit.type }}</li>
        </ul>

        
        <ul class="product-links">
            <li>Marque:</li>
            <li>{{ produit.marque.nom }} [ {{ produit.marque.fournisseur.nom }} ]</li>
        </ul>

    </div>
</div>
<!-- /Product details -->
{% endblock %}